:toc: macro
:toc-title:

# react-popover

image:https://travis-ci.org/littlebits/react-popover.svg?branch=master["Build Status", link="https://travis-ci.org/littlebits/react-popover"]


toc::[]

## React Versions Support

`react-popover` `>= 0.5.0` supports React 16 while `react-popover` `< 0.5.0` works with React `15.x.x` and likely lower. There is no plan to support older versions of this library with back-ported patches and PRs for that purpose are not welcome since it increases maintenance for the authors.

## Installation

```
yarn add react-popover
```

## Examples

Look at the link:https://littlebits.github.io/react-popover[stories in our storybook].

## Basics

React-popover is a lightweight responsive popover.
```
import Popover from 'react-popover';

<Popover
  body="Im the content of the responsive popover"
  isOpen
>
<div>I am a popover</div>
</Popover>
```
____
You should not set target prop and children at the same time since both refer to the node on which the Popover would be displayed.
____

## Placements

Placement of a popover is controlled by two props: `preferPlace` and `place` with these available options.

`above | right | below | left` :: Prefer an explicit side.
`row | column` :: Prefer an orientation.
`start | end` :: Prefer an order.
`null` :: No preference, automatic resolution. This is the default.

If none is set, Popover will automatically resolve the placement of popover on target node with a highly responsive behavior.
Popover automatically resolves and set its placement to the side of target with most space.
For instance, if target has more space on the right than any other side, the popover will be rendered to the right of the target.


if `preferPlace` is set (say `above`), popover will be rendered to `above` only if there is enough space to render overlay. If space above doesnt fit, the side with the max space will be the placement of Popover.
`preferPlace` can be scoped to an orientation using `row` and `column`. If `preferPlace` is set to `row, for instance, Popover will resolve to any of `above` and `below` only if they fit else the next placement with the max space would be used.

____
`row` maps to `above` and `below`
`column` maps to `left` and `right`
____


```jsx harmony
<Popover
  body="Im the content of the highly responsive popover"
  isOpen
  preferPlace="top"
>
<div>I am a popover</div>
</Popover>
```
The rest (placement point on target and location of arrow on popover) is responsively taken care of.
The position of arrow will be located at the center of Popover and point to the center of the target node by default.
If there isnt enough space to render at the centers, arrow pointer will be automatically shifted to different at the same placement position.
Take a look at this link:https://littlebits.github.io/react-popover[example].

```jsx harmony
<Popover
  body="Im the content of the highly responsive popover"
  isOpen
  preferPlace="top"
  place="bottom"
>
<div>I am a popover</div>
</Popover>
```
____
`place` props overrides `preferPlace` since `place` is set as a scope constant.
____

## API

.Table React-popover
|===
|Column Name |Column Required |Column type |Column default|Column description

|Column 1, `body`
|Column 2, true
|Column 3, any
|Column 4, `undefined`
|Column 5, Content of popover.

|Column 1, `isOpen`
|Column 2, false
|Column 3, any
|Column 4, false
|Column 5, Shows popover overlay if set to true.

|Column 1, `preferPlace`
|Column 2, false
|Column 3, link:#placements[Placement] enum
|Column 4, `undefined`
|Column 5, Preferred placement of popover if multiple placements have enough space to render popover.

|Column 1, `place`
|Column 2, false
|Column 3,  link:#placements[Placement] enum
|Column 4, `undefined`
|Column 5, Constant (scoped) placement of popover regardless of availability of more fitting placement. Read link:L97[Placement].

|Column 1, `onOuterAction`
|Column 2, false
|Column 3,  `(SyntheticEvent<*>) => void`
|Column 4, `undefined`
|Column 5, A callback function executed every time the user does an action (`mousedown` or `touchstart`) outside the DOM tree of both `Popover` and `Target`. A canonical use-case is to automatically close the Popover on any external user action.

|Column 1, `refreshIntervalMs`
|Column 2, false
|Column 3, `number`, `boolean: false`
|Column 4, 200ms
|Column 5, The polling speed (AKA time interval between each poll) in milliseconds for checking if a layout refresh is required. This polling is required because it is the only robust way to track the position of a target in the DOM. Defaults to `200`. Set to a `false` value to disable.

|Column 1, `enterExitTransitionDurationMs`
|Column 2, false
|Column 3, `number`, `boolean: false`
|Column 4, 500ms
|Column 5, The amount of time in milliseconds that it takes to complete the enter and exit animation.

|Column 1, `tipSize`
|Column 2, false
|Column 3, `number`
|Column 4, 7
|Column 5, Defines the size of the arrow tip pointer. Set to 0.01 to disable tip.

|Column 1, `target`
|Column 2, false
|Column 3, `React$Node`
|Column 4, `undefined`
|Column 5, The React Node that this popover will orient itself around. `target` rendering tree is unaffected. `Popover` _will_ become its `owner`. This can also be set as `children`.

|Column 1, `appendTarget`
|Column 2, false
|Column 3, `React$Portal` read https://reactjs.org/docs/portals.html[Portal]
|Column 4, `undefined`
|Column 5, Usually Popover is mounted as a child of `document.body` for consistent layout. If `appendTarget` is set, Popover will render as a child of `appendTarget` instead of `document.body`.
|===

____
 Standard React properties like `className` and `style` are passed on to the overlay container element.
____
